/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author duyplus
 */
public final class LOADING extends javax.swing.JFrame {

    /**
     * Creates new form LoadingForm
     */
    public LOADING() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtText = new javax.swing.JLabel();
        lblHinh5 = new javax.swing.JLabel();
        lblHinh3 = new javax.swing.JLabel();
        lblHinh1 = new javax.swing.JLabel();
        lblHinh2 = new javax.swing.JLabel();
        lblHinh4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        pbLoad = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtText.setForeground(new java.awt.Color(255, 255, 255));
        txtText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtText.setText("LOADING");
        jPanel1.add(txtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 780, 20));

        lblHinh5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh5.png"))); // NOI18N
        jPanel1.add(lblHinh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 250, 260));

        lblHinh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh3.png"))); // NOI18N
        jPanel1.add(lblHinh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 260, 240));

        lblHinh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh1.png"))); // NOI18N
        jPanel1.add(lblHinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 220));

        lblHinh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh2.png"))); // NOI18N
        jPanel1.add(lblHinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 260));

        lblHinh4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh4.png"))); // NOI18N
        jPanel1.add(lblHinh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 260, 250));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 240, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MANAGER STUDENTS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 300, 40));

        pbLoad.setForeground(new java.awt.Color(153, 153, 0));
        jPanel1.add(pbLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 484, 910, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loading.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOADING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOADING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOADING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOADING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LOADING ld = new LOADING();
        ld.setVisible(true);
        try {
            for (int i = 0; i <= 110; i += 10) {
                Thread.sleep(200);
                ld.pbLoad.setStringPainted(true);
                if (i == 10) {
                    ld.txtText.setText("Bạn có biết bạn sẽ không thể vừa thở vừa uống nước không?");
                }
                if (i == 20) {
                    ld.txtText.setText("Bạn có biết các bông hoa sẽ nở nhanh hơn nếu được nghe nhạc!");
                }
                if (i == 30) {
                    ld.txtText.setText("Con đường dài nhất không phải là đường đi mà chính là đường đời!");
                }
                if (i == 40) {
                    ld.txtText.setText("Theo nghiên cứu người nào có IQ càng cao sẽ mơ nhiều hơn bình thường!");
                }
                if (i == 50) {
                    ld.txtText.setText("Bạn có biết cơ quan quan trọng nhất của phụ nữ là gì không?");
                }
                if (i == 60) {
                    ld.txtText.setText("Nếu ô tô có thể bay nó chỉ mất khoảng 1 giờ để ra ngoài vũ trụ");
                }
                if (i == 70) {
                    ld.txtText.setText("Quả bóng bằng thủy tinh có thể nảy cao hơn quả bóng bằng cao su");
                }
                if (i == 80) {
                    ld.txtText.setText("75% con người trên Trái Đất chưa từng thấy tuyết");
                }
                if (i == 90) {
                    ld.txtText.setText("Woa, load sắp xong dữ liệu rồi nè...");
                }
                if (i == 100) {
                    Thread.sleep(500);
                    ld.txtText.setText("Chúc bạn sử dụng phần mềm của tôi vui vẻ và an toàn <3");
                }
                if (i == 110) {
                    ld.dispose();
                    new LOGIN().setVisible(true);
                }
                ld.pbLoad.setValue(i);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHinh1;
    private javax.swing.JLabel lblHinh2;
    private javax.swing.JLabel lblHinh3;
    private javax.swing.JLabel lblHinh4;
    private javax.swing.JLabel lblHinh5;
    private javax.swing.JProgressBar pbLoad;
    private javax.swing.JLabel txtText;
    // End of variables declaration//GEN-END:variables
}
