/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Vector;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.DiemSV;
import model.Excel;
import utils.JDBCUtils;

/**
 *
 * @author duyplus
 */
public final class QLGV extends javax.swing.JFrame {

    ArrayList<DiemSV> list = new ArrayList<>();
    DefaultTableModel model;
    // Biến dùng chung
    int index = 0;
    public static Connection conn = null; // Kết nối với sql
    public static PreparedStatement ps = null; // Câu lệnh SQL được biên dịch trước
    public static Statement st = null; // Thi hành câu lệnh tùy ý tại thời điểm chạy
    public static ResultSet rs = null; // Trả về kết quả truy vấn

    /**
     * Creates new form QLD
     */
    public QLGV() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(231, 228, 190));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        conn = JDBCUtils.getConnection();

        model = (DefaultTableModel) tblQLD.getModel();
        model.setRowCount(0);
        list = getGrade();
        loadDbTable();

        tblQLD.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblQLD.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblQLD.getColumnModel().getColumn(2).setPreferredWidth(10);
        tblQLD.getColumnModel().getColumn(3).setPreferredWidth(10);
        tblQLD.getColumnModel().getColumn(4).setPreferredWidth(10);
        tblQLD.getColumnModel().getColumn(5).setPreferredWidth(10);
        tblQLD.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMaSV = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblTiengAnh = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        lblTinHoc = new javax.swing.JLabel();
        txtTH = new javax.swing.JTextField();
        lblGDTC = new javax.swing.JLabel();
        txtGD = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDiemTB = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLD = new javax.swing.JTable();
        btnSendmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ ĐIỂM SINH VIÊN");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("QUẢN LÝ ĐIỂM SINH VIÊN");
        lblTitle.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(30, 139, 195));

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setText("TÌM KIẾM");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setMargin(new java.awt.Insets(2, 4, 2, 4));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaSV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaSV.setText("MÃ SINH VIÊN");
        jPanel3.add(lblMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtMaSV.setEditable(false);
        txtMaSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaSV.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jPanel3.add(txtMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 30));

        lblHoTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHoTen.setText("TÊN SINH VIÊN ");
        jPanel3.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtHoTen.setEditable(false);
        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoTen.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jPanel3.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 30));

        lblTiengAnh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTiengAnh.setText("TIẾNG ANH");
        jPanel3.add(lblTiengAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtTA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTA.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jPanel3.add(txtTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, 30));

        lblTinHoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTinHoc.setText("TIN HỌC");
        jPanel3.add(lblTinHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtTH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTH.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jPanel3.add(txtTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, 30));

        lblGDTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGDTC.setText("GIÁO DỤC THỂ CHẤT");
        jPanel3.add(lblGDTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtGD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGD.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jPanel3.add(txtGD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, 30));

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnAdd.setText("LÀM MỚI");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAdd.setIconTextGap(10);
        btnAdd.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 200, 45));

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        btnSave.setText("THÊM ĐIỂM");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSave.setIconTextGap(10);
        btnSave.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 45));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnUpdate.setText("CẬP NHẬT ĐIỂM");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnUpdate.setIconTextGap(10);
        btnUpdate.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 200, 45));

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setText("XÓA ĐIỂM");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDelete.setIconTextGap(10);
        btnDelete.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 200, 45));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnFirst.setBackground(new java.awt.Color(255, 0, 51));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/first.png"))); // NOI18N
        btnFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(255, 0, 51));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prev.png"))); // NOI18N
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(255, 0, 51));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(255, 0, 51));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/last.png"))); // NOI18N
        btnLast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));

        jPanel6.setBackground(new java.awt.Color(0, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("ĐIỂM TRUNG BÌNH");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(75, 75, 75))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        lblDiemTB.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDiemTB.setForeground(new java.awt.Color(255, 255, 255));
        lblDiemTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnExport.setBackground(new java.awt.Color(0, 153, 255));
        btnExport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/export.png"))); // NOI18N
        btnExport.setText("XUẤT EXCEL");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("3 sinh viên có điểm cao nhất:");

        tblQLD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblQLD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SV", "HỌ TÊN", "TIẾNG ANH", "TIN HỌC", "GDTC", "ĐIỂM TB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQLD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblQLD.setFillsViewportHeight(true);
        tblQLD.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblQLD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLD);

        btnSendmail.setBackground(new java.awt.Color(0, 153, 255));
        btnSendmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSendmail.setForeground(new java.awt.Color(255, 255, 255));
        btnSendmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/email.png"))); // NOI18N
        btnSendmail.setText("GỬI EMAIL");
        btnSendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSendmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchGrade();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addGrade();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveGrade();
        addGrade();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        index = tblQLD.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hàng cần xóa!");
        } else {
            deleteGrade();
            addGrade();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        index = tblQLD.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hàng cần cập nhật!");
        } else {
            updateGrade();
            addGrade();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblQLDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLDMouseClicked
        // TODO add your handling code here:
        int row = tblQLD.getSelectedRow();
        showDetail(row);
    }//GEN-LAST:event_tblQLDMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        index = 0;
        showDetail(index);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        if (index > 0) {
            index--;
            showDetail(index);
        } else {
            return;
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if (index < list.size() - 1) {
            index++;
            showDetail(index);
        } else {
            return;
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        index = list.size() - 1;
        showDetail(index);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        Excel ex = new Excel();
        ex.exGrade();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnSendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendmailActionPerformed
        // TODO add your handling code here:
        sendMail();
    }//GEN-LAST:event_btnSendmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
//                boolean ok = true;
//                int msg = JOptionPane.showConfirmDialog(null, "Bạn cần phải đăng nhập để truy cập trang quản lý!"
//                        + "\n(CHỈ DÀNH CHO GIẢNG VIÊN)"
//                        + "\n\n                (Chọn 'YES' để tiếp tục)", "THÔNG BÁO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
//                if (msg == JOptionPane.YES_OPTION) {
//                    if (ok) {
//                        new LOGIN().setVisible(true);
//                    } else {
                new QLGV().setVisible(true);
//                    }
//                } else {
//                    return;
//                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSendmail;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JLabel lblGDTC;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaSV;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTiengAnh;
    private javax.swing.JLabel lblTinHoc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblQLD;
    private javax.swing.JTextField txtGD;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTA;
    private javax.swing.JTextField txtTH;
    // End of variables declaration//GEN-END:variables

    public ArrayList<DiemSV> getGrade() {
        try {
            conn = JDBCUtils.getConnection();
            String sql = "SELECT STUDENTS.MASV,HOTEN,TIENGANH,TINHOC,GDTC,(TIENGANH+TINHOC+GDTC)/3 AS TBM "
                    + " FROM STUDENTS"
                    + " INNER JOIN GRADES ON STUDENTS.MASV = GRADES.MASV"
                    + " ORDER BY TBM DESC";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                DiemSV sv = new DiemSV();
                sv.setMaSV(rs.getString("MASV"));
                sv.setTenSV(rs.getString("HOTEN"));
                sv.setAnh(Double.parseDouble(rs.getString("TIENGANH")));
                sv.setTin(Double.parseDouble(rs.getString("TINHOC")));
                sv.setGdtc(Double.parseDouble(rs.getString("GDTC")));
                sv.setAvg(Double.parseDouble(rs.getString("TBM")));
                list.add(sv);
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
        return list;
    }

    public void diemTb() {
        double TA = Double.parseDouble(txtTA.getText());
        double TH = Double.parseDouble(txtTH.getText());
        double GDTC = Double.parseDouble(txtGD.getText());
        double dtb = (TA + TH + GDTC) / 3;
        String kq = String.format("%.2f", dtb);
        lblDiemTB.setText(kq + "");
    }

    public void showDetail(int row) {
        row = tblQLD.getSelectedRow();
        txtMaSV.setText(tblQLD.getValueAt(row, 0).toString());
        txtHoTen.setText(tblQLD.getValueAt(row, 1).toString());
        txtTA.setText(tblQLD.getValueAt(row, 2).toString());
        txtTH.setText(tblQLD.getValueAt(row, 3).toString());
        txtGD.setText(tblQLD.getValueAt(row, 4).toString());
        diemTb();
    }

    public void loadDbTable() {
        try {
            model.setRowCount(0);
            conn = JDBCUtils.getConnection();
            st = conn.createStatement();
            String sql = "SELECT TOP 3 STUDENTS.MASV AS MASV,HOTEN,TIENGANH,TINHOC,GDTC,(TIENGANH+TINHOC+GDTC)/3 AS TBM "
                    + " FROM STUDENTS, GRADES WHERE STUDENTS.MASV = GRADES.MASV "
                    + " ORDER BY TBM DESC";
            rs = st.executeQuery(sql);
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Chưa có sinh viên nào!");
                return;
            }
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("MASV"));
                row.add(rs.getString("HOTEN"));
                row.add(Double.parseDouble(rs.getString("TIENGANH")));
                row.add(Double.parseDouble(rs.getString("TINHOC")));
                row.add(Double.parseDouble(rs.getString("GDTC")));
                double TA = Double.parseDouble(rs.getString("TiengAnh"));
                double TH = Double.parseDouble(rs.getString("TinHoc"));
                double GDTC = Double.parseDouble(rs.getString("GDTC"));
                double DTB = (TA + TH + GDTC) / 3;
                String diemTb = String.format("%.2f", DTB);
                row.add(diemTb);
                model.addRow(row);
            }
            tblQLD.setModel(model);
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void searchGrade() {
        try {
            //model.setRowCount(0);
            conn = JDBCUtils.getConnection();
            String sql = "SELECT * FROM STUDENTS WHERE MASV = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtSearch.getText());
            rs = ps.executeQuery();
            boolean isOk = false;
            while (rs.next()) {
                JOptionPane.showMessageDialog(this, "Đã tìm thấy sinh viên!");
                txtMaSV.setText(rs.getString(1));
                txtHoTen.setText(rs.getString(2));
                isOk = true;
            }
            if (!isOk) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên!");
                txtMaSV.requestFocus();
            }
            conn.close();
            loadDbTable();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void addGrade() {
        txtHoTen.setText("");
        txtMaSV.setText("");
        txtTA.setText("");
        txtTH.setText("");
        txtGD.setText("");
        lblDiemTB.setText("");
    }

    public void saveGrade() {
        try {
            model.setRowCount(0);
            conn = JDBCUtils.getConnection();
            String sql = "INSERT INTO GRADES(MASV, TIENGANH, TINHOC, GDTC) VALUES ( ?, ?, ?, ?)";
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtMaSV.getText());
            ps.setDouble(2, Double.parseDouble(txtTA.getText()));
            ps.setDouble(3, Double.parseDouble(txtTH.getText()));
            ps.setDouble(4, Double.parseDouble(txtGD.getText()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Lưu điểm sinh viên thành công!");
            conn.close();
            loadDbTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Thất bại!");
        }
    }

    public void deleteGrade() {
        try {
            conn = JDBCUtils.getConnection();
            String sql = "DELETE FROM GRADES WHERE MASV = ?";
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá điểm của sinh viên này không?",
                    "THÔNG BÁO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                ps = conn.prepareStatement(sql);
                ps.setString(1, txtMaSV.getText());
                ps.executeUpdate();
                list.remove(index);
                JOptionPane.showMessageDialog(this, "Xóa điểm sinh viên thành công!");
            }
            conn.close();
            loadDbTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Thất bại!");
        }
    }

    public void updateGrade() {
        try {
            model.setRowCount(0);
            conn = JDBCUtils.getConnection();
            String sql = "UPDATE GRADES SET TIENGANH = ?, TINHOC = ?, GDTC = ? WHERE MASV = ? ";
            ps = conn.prepareStatement(sql);
            ps.setDouble(1, Double.parseDouble(txtTA.getText()));
            ps.setDouble(2, Double.parseDouble(txtTH.getText()));
            ps.setDouble(3, Double.parseDouble(txtGD.getText()));
            ps.setString(4, txtMaSV.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhật điểm sinh viên thành công!");
            conn.close();
            loadDbTable();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thất bại!");
        }
    }

    public void sendMail() {
        try {
            String fromacc = "duyplus147@gmail.com";
            String frompass = "gavkl123";
            Properties props = new Properties();
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "587");
            Session ss = Session.getDefaultInstance(props, new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(fromacc, frompass);
                }
            });
            String sql = "SELECT * FROM STUDENTS WHERE MASV = ?";
            conn = JDBCUtils.getConnection();
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtMaSV.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                String to = rs.getString("Email");
                String subject = "BẢNG ĐIỂM HỌC KÌ | FPT POLYTECHNIC";
                String body = "<div style='font-size:20px;background-color:cyan;padding:10px;'>"
                        + "<h3>Chào bạn, đây là bảng điểm học kì vừa rồi từ giảng viên gửi cho bạn!</h3>"
                        + "<hr>Mã SV: <b>" + txtMaSV.getText() + "</b><br>Họ Tên: <b>" + txtHoTen.getText() + "</b>"
                        + "<hr>Tiếng Anh: <b>" + txtTA.getText() + "</b><br>Tin Học: <b>" + txtTH.getText() + "</b><br>Giáo Dục Thể Chất: <b>" + txtGD.getText() + "</b></div>";
                MimeMessage msg = new MimeMessage(ss);
                msg.setFrom(new InternetAddress(fromacc));
                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
                msg.setSubject(subject, "utf-8");
                msg.setContent(body, "text/html;charset=UTF-8");

                Transport.send(msg);
                JOptionPane.showMessageDialog(this, "The e-mail has been sent successfully!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            System.out.println("" + e);
        }
    }
}
